### ISSUE TITLE
Bikeshed `std::dynamic_extent`

### ISSUE THREAD

**Issue by brycelelbach** [ORNL/cpp-proposals-pub#14]
We should consider asking for `std::dyn`; `std::dynamic_extent` is unnecessarily verbose.

**Comment by crtrott** [comment]
Do we still want to do this?

**Comment by dhollman** [comment]
No. LEWG used `std::dynamic_extent` for `span`. There's no reason to deviate from `span` in this matter.

**Comment by crtrott** [comment]
Ok closing.
