### ISSUE TITLE
Remove the appendices

### ISSUE THREAD

**Issue by brycelelbach** [ORNL/cpp-proposals-pub#18]
The appendices to P0009 discuss a number of alternatives/enhancements that could be made to P0009 if other proposals successfully get through the committee.

At this point, given that P0009 is close to advancing to a plenary vote, we should remove these appendices. None of the things in the appendix are actually part of the proposal. That might make you think that they are harmless to include. However, the fact that they **are** in the proposal may confuse people, especially committee members who are unfamiliar with the proposal and may skim it instead of reading it entirely.

We do not want people to raise objections to P0009 in plenary because they looked through the paper, saw something that they disliked in the appendices, and assumed it was part of the proposal.

A list to prior/related papers should be sufficient.

**Comment by crtrott** [comment]
I believe this was done.
