### ISSUE TITLE
P1673: Fix wording to permit user-defined complex number types

### ISSUE THREAD

**Issue by mhoemmen** [ORNL/cpp-proposals-pub#236]
## Summary

Thanks to @PhilMiller for an excellent discussion about this!  I've written some text to add to the introduction, but we also need normative wording changes.  The essence is to replace uses of `conj` in the wording with an exposition-only function _`conj-if-needed`_, defined as follows:

```
template<class T>
T <it>conj-if-needed</it>(const T& t)
{
    using std::conj;
    return conj(t);
}

template<class T> requires is_arithmetic_v<T>
T <it>conj-if-needed</it>(const T& t)
{
    return t;
}
```

If we needed actual words for this, we could borrow them from `iter_swap`'s wording.  Here follows a draft of the text.

## Support for user-defined complex number types

The C++ Standard currently supports `complex<T>` for T = `float`, `double`, and `long double`.  Users who want complex numbers of other types (such as integers or custom "bigfloat" types), or who have different alignment requirements for complex numbers, need to make their own complex number class (or class template).  We want P1673 to "do the right thing" for these custom complex numbers, without requiring any more number traits machinery than the Standard already has.  This means relying on ADL to pick up overloads of `conj`, and not defining any new traits (such as `is_complex`).  The idiom of `using std::conj; return conj(x);`, analogous to how `iter_swap` accesses `swap`, can manage this.  Here is an example with a user-defined complex number class template `MyComplex`.

```c++
#include <cassert>
#include <complex>

namespace MyNamespace {

template<class Real>
struct MyComplex {
    Real real;
    Real imag;
};

template<class Real>
MyComplex<Real> conj(const MyComplex<Real>& z) {
    return {z.real, -z.imag};
}

} // MyNamespace

int main() {
    using std::conj;

    MyNamespace::MyComplex<int> z{3, 4};
    const auto z_conj = conj(z);
    assert(z_conj.real == 3);
    assert(z_conj.imag == -4);

    std::complex<double> w{5.0, 6.0};
    const auto w_conj = conj(w);
    assert(w_conj.real() == 5.0);
    assert(w_conj.imag() == -6.0);
    return 0;
}
```

Regarding alignment: The Standard explicitly specifies that `complex<T>` has the same alignment as `T[2]`.  That's not so friendly for GPUs and SIMD.  `Kokkos::complex` also exists because a few years ago, we had to bless its member functions with `__host__` `__device__` .)  (I wrote `Kokkos::complex` back then, so that we could build Trilinos with complex number support on GPUs.)

If we define `accessor_conjugate` to do `using std::conj; return conj(x);`, then we can support custom complex class templates.  Users can define `conj` for their custom complex type outside the `std` namespace, and this approach will pick it up, analogous to how `iter_swap` can pick up a custom `swap` overload.  However, this will do the wrong thing for built-in (non-complex) arithmetic types like `double` or `int`.  This is because `std::conj` is defined always to return a specialization of `complex`, even if the input is (say) `double`.

One could argue that applying `conjugated` to a view of real numbers *should* be ill formed.  However, users may want to use `conjugate_transposed` to write generic code that works for both real and complex numbers.  Matlab takes this approach, by defining the `'` (single quote) operator to take the conjugate transpose if its argument is complex, and the transpose if its argument is real.  BLAS also supports this to some extent, by having its real routines like `DGEMM` interpret `TRANSA='C'` as the transpose.

We can support `conjugated` (and thus `conjugated_transposed`) for all types as follows.

1. For arithmetic types, define `accessor_conjugate` specially to return just the reference.  Don't use `conj` at all.

2. For all other types (including specializations of `complex`), define `accessor_conjugate` to use `using std::conj; return conj(x);`.

We could express this through an exposition-only function _`conj-if-needed`_:

```
template<class T>
T <it>conj-if-needed</it>(const T& t)
{
    using std::conj;
    return conj(t);
}

template<class T> requires is_arithmetic_v<T>
T <it>conj-if-needed</it>(const T& t)
{
    return t;
}
```

Even though it's possible to write "generic" (real or complex) linear algebra code using `conjugate_transposed`, it's still important to distinguish between symmetric and Hermitian matrix algorithms.  This is because symmetric does *not* mean the same thing as Hermitian for matrices of complex numbers.  Complex symmetric matrices are useful in practice, for example when modeling damped vibrations (Craven 1969).

B. D. Craven, ["Complex symmetric matrices"](https://doi.org/10.1017/S1446788700007588), *Journal of the Australian Mathematical Society*, Vol. 10, No. 3-4, Nov. 1969, pp. 341--354.

Credit to Phil Miller (`phil.miller@intensecomputing.com`) for pointing out a wording issue that would have hindered use of user-defined complex types.

**Comment by PhilMiller** [comment]
Going the other way now, I think the adjusted wording will make non-complex user defined types unhappy. `class MyBigInt` will neither satisfy `is_arithmetic` nor have a definition of `conj`. I think detection of the validity of `conj(T)` via SFINAE or the like might be the most appropriate approach.

**Comment by mhoemmen** [comment]
Thanks Phil for the suggestion!  It's a great idea, but if users write a custom complex type and forget or misspell `conj`, then SFINAE detection will generate silently incorrect code.  The problem I'm trying to work around with `conj-if-needed` is that `conj` has the wrong return type (complex) for (real) arithmetic type parameters.  If users type `conjugated(A)` or `conjugate_transposed(A)`, then it's reasonable to expect `conj` to be defined for `A`'s value type.

In general, P1673 avoids defining traits classes or other code machinery for reasoning about generic number behavior.  Detection of `conj` doesn't _quite_ go there, but might lead users and implementers down the path of asking for a "complex number" concept.  The P1673 approach is for each algorithm to require only what that algorithm needs.

Nevertheless, I think this is a good question for design review.  (Reviewers need some concrete questions to answer, so we don't get the "uh... this is big... **silence**" response again ; - ) .)

**Comment by mhoemmen** [comment]
New draft, that presents Phil's suggestion as a design alternative and asks LEWG to pick one.

## Support for user-defined complex number types

### Need for user-defined complex number types

The C++ Standard currently supports `complex<T>` for T = `float`, `double`, and `long double`.  Users who want complex numbers of other types (such as integers or custom "bigfloat" types), or who have different alignment requirements for complex numbers, need to make their own complex number class (or class template).  We want P1673 to "do the right thing" for these custom complex numbers, without requiring any more number traits machinery than the Standard already has.  This means relying on ADL to pick up overloads of `conj`, and not defining any new traits (such as `is_complex`).  The idiom of `using std::conj; return conj(x);`, analogous to how `iter_swap` accesses `swap`, can manage this.  Here is an example with a user-defined complex number class template `MyComplex`.

```c++
#include <cassert>
#include <complex>

namespace MyNamespace {

template<class Real>
struct MyComplex {
    Real real;
    Real imag;
};

template<class Real>
MyComplex<Real> conj(const MyComplex<Real>& z) {
    return {z.real, -z.imag};
}

} // MyNamespace

int main() {
    using std::conj;

    MyNamespace::MyComplex<int> z{3, 4};
    const auto z_conj = conj(z);
    assert(z_conj.real == 3);
    assert(z_conj.imag == -4);

    std::complex<double> w{5.0, 6.0};
    const auto w_conj = conj(w);
    assert(w_conj.real() == 5.0);
    assert(w_conj.imag() == -6.0);
    return 0;
}
```

Regarding alignment: The Standard explicitly specifies that `complex<T>` has the same alignment as `T[2]`.  That's not so friendly for GPUs and SIMD.  `Kokkos::complex` also exists because a few years ago, we had to bless its member functions with `__host__` `__device__` .)  (One of the authors wrote `Kokkos::complex` to make it possible to build Trilinos with complex number support on GPUs.)

### Users may want to conjugate arithmetic types

If we define `accessor_conjugate` to do `using std::conj; return conj(x);`, then we can support custom complex class templates.  Users can define `conj` for their custom complex type outside the `std` namespace, and this approach will pick it up, analogous to how `iter_swap` can pick up a custom `swap` overload.  However, this will do the wrong thing for built-in (non-complex) arithmetic types like `double` or `int`.  This is because `std::conj` is defined always to return a specialization of `complex`, even if the input is (say) `double`.

One could argue that applying `conjugated` to a view of real numbers *should* be ill formed.  However, users may want to use `conjugate_transposed` to write generic code that works for both real and complex numbers.  Matlab takes this approach, by defining the `'` (single quote) operator to take the conjugate transpose if its argument is complex, and the transpose if its argument is real.  BLAS also supports this to some extent, by having its real routines like `DGEMM` interpret `TRANSA='C'` as the transpose.  Krylov subspace methods in Trilinos' Anasazi and Belos packages also follow a Matlab-like generic approach.

Even though we think it should be possible to write "generic" (real or complex) linear algebra code using `conjugate_transposed`, we still need to distinguish between symmetric and Hermitian matrix algorithms.  This is because symmetric does *not* mean the same thing as Hermitian for matrices of complex numbers.  For example, a matrix whose off-diagonal elements are all `3 + 4i` is symmetric, but not Hermitian.  Complex symmetric matrices are useful in practice, for example when modeling damped vibrations (Craven 1969).

### Our proposed approach

We can support `conjugated` (and thus `conjugated_transposed`) for all types as follows.

1. For arithmetic types, define `accessor_conjugate` specially to return just the reference.  Don't use `conj` at all.

2. For all other types (including specializations of `complex`), define `accessor_conjugate` to use `using std::conj; return conj(x);`.

We could express this through an exposition-only function _`conj-if-needed`_:

```
template<class T>
T <it>conj-if-needed</it>(const T& t)
{
    using std::conj;
    return conj(t);
}

template<class T> requires is_arithmetic_v<T>
T <it>conj-if-needed</it>(const T& t)
{
    return t;
}
```

### Alternative: Always treat user-defined types as real

One issue with the above approach is that `conjugated` will fail to compile for user-defined (and thus nonarithmetic) types, unless the type has `conj` defined.  If a generic library of linear algebra algorithms uses `conjugate_transposed` throughout to express transposition, then users of this library could have an unpleasant surprise when they move from arithmetic types to custom real types.

One could fix this by introducing an exposition-only function _`conj-if-not-arithmetic`_ that applies `conj` in the above two-step manner to nonarithmetic types, and an exposition-only concept _`conjugatable`_ for whether calling _`conj-if-not-arithmetic`_ on the type is well formed.  For example:

```c++
template<class T>
T <it>conj-if-not-arithmetic</it>(const T& t)
{
    using std::conj;
    return conj(t);
}

template<class T> requires is_arithmetic_v<T>
T <it>conj-if-not-arithmetic</it>(const T& t)
{
    return t;
}

template<class T>
concept <it>conjugatable</it> = requires(T a)
{ // "using" declarations don't work in here
    T b = <it>conj-if-not-arithmetic</it>(a);
}

template<class T>
T <it>conj-if-needed</it>(const T& t)
{
    return t;
}

template<conjugatable T>
T <it>conj-if-needed</it>(const T& t)
{
    return <it>conj-if-not-arithmetic</it>(t);
}
```

However, if users write a custom complex type and forget or misspell `conj`, then this alternative will make `conjugated` and `conjugate_transposed` silently incorrect.  The intent of our proposed approach is to work around the problem of `conj` *existing*, but having a *different return type* (complex) for arithmetic (and therefore real) parameters.  If users type `conjugated(A)` or `conjugate_transposed(A)`, then we think it reasonable to expect `conj` to be defined for `A`'s value type.  Users of custom number types can supply a trivial definition of `conj`, even if the number type itself does not provide one.

In general, we avoid defining traits classes or other code machinery for reasoning about generic number behavior.  Detection of `conj` doesn't *quite* go there, but might lead users and implementers down the path of asking for a "complex number" concept.  The P1673 way, which we believe is the C++ Standard Algorithms way, is for each algorithm to require only what that algorithm needs.

### Design question

Please pick one of the following:

1. (Our proposal) `conjugated` and `conjugate_transposed` assume that `using std::conj; T b = conj(a);` is well formed for any nonarithmetic type `T`.

2. (Alternative) `conjugated` and `conjugate_transposed` do not use `conj` if `using std::conj; T b = conj(a);` is not well formed for nonarithmetic `T`.

---

B. D. Craven, ["Complex symmetric matrices"](https://doi.org/10.1017/S1446788700007588), *Journal of the Australian Mathematical Society*, Vol. 10, No. 3-4, Nov. 1969, pp. 341--354.

Credit to Phil Miller (`phil.miller@intensecomputing.com`) for pointing out this issue.

**Comment by PhilMiller** [comment]
Can I suggest that the design question not be posed as a strict dilemma of the options provided? The reviewers won't limit themselves to those anyway, but it will skew at least some of their thinking.

I'll posit at least a few other alternatives:
- An `is_complex<T>` trait, with suitable wording to allow some means of definition for user-defined types `T`
- Making `conjugate_if_needed` concrete, defining it for the arithmetic types and `std::complex`, and making it a customization point for user-defined types. Require that `conjugate_if_needed(t)` be well-formed where appropriate. This leaves no room for the silent errors mentioned. The naming of this can be bike-shedded.

**Comment by mhoemmen** [comment]
@PhilMiller wrote:
> The reviewers won't limit themselves to those anyway, but it will skew at least some of their thinking.

In this case, I very much want to skew their thinking ; - ) .  I would personally vote against an `is_complex` trait, so I don't want to list the option.

The idea is that `conjugated` calls `conj`.  The special case of arithmetic types is for the BLAS' sake and nothing else. 
 The `conj` function _is_ the customization point; it already exists, and I don't want to introduce a new one.  We very much want to stay out of the business of number traits.  P1673 implements algorithms, not "number stuff."

**Comment by mhoemmen** [comment]
@PhilMiller We got feedback from LEWG on this discussion.  I'll be recording that as a separate issue.  Summary is that they like the idea of making a customization point available.  We plan to split that off into a separate paper, and go ahead for now with `conjugated` just calling `std::conj` for `std::complex`.

**Comment by PhilMiller** [comment]
Thanks for the update. I'm glad to hear things will move ahead, and custom types will eventually be well supported. It makes sense to prioritize the built in arithmetic types and std::complex.

**Comment by mhoemmen** [comment]
Here's the issue: https://github.com/ORNL/cpp-proposals-pub/issues/248
