### ISSUE TITLE
P1673: Spawn conj-if-needed into named customization point in a separate paper

### ISSUE THREAD

**Issue by mhoemmen** [ORNL/cpp-proposals-pub#248]
In LEWG review of P1673R8 today (2022/05/24), LEWG asked that we turn the exposition-only function `conj-if-needed` into a user-visible customization point (named `std::conjugate` or something like that).  The customization point could ADL-find `conj` if it exists, so that it could be compatible with existing custom complex types that aim to be syntactically compatible with `std::complex`.

This approach would make conjugation type-preserving, unlike `std::conj`, which turns "DoubleOrInteger" into `std::complex`.  The resulting customization point would be more ergonomic for users.

We plan the following:

1. For now, restrict `conjugated` to non-custom types: `std::complex` or arithmetic types.
2. Mention in P1673 that we plan to write a separate paper with a customization point.
3. Write a separate proposal for a customization point, `std::conjugate`.  Propose it as a niebloid for now, but ask LEWG to poll on the customization point mechanism.  (This is better than waiting on WG21 to decide on a customization point syntax or mechanism.)
4. Add a follow-on paper to P1673 that uses the customization point in `conjugated`, so that it can work with custom number types.

**Comment by PhilMiller** [comment]
I'm happy to work on that follow-on paper, given that it's a result of my complaint.

**Comment by mhoemmen** [comment]
@PhilMiller Thanks!  We'll be happy to have your help with that.

**Comment by mhoemmen** [comment]
Fixed in R9, using SG6 small group's preferred solution, rather than LEWG's preferred solution.
