### ISSUE TITLE
P0009 LayoutStride Wording

### ISSUE THREAD

**Issue by crtrott** [ORNL/cpp-proposals-pub#31]
```c++
struct layout_stride {
  template <typename Extents>
  class mapping {
  public:
    constexpr mapping() noexcept;
    constexpr mapping(mapping const& other) noexcept;
    constexpr mapping(mapping&& other) noexcept;
    constexpr mapping(Extents e, array<ptrdiff_t, Extents::rank()> s) noexcept;
    template<class OtherExtents>
      constexpr mapping(const mapping<OtherExtents>& other);

    mapping& operator=() noexcept = default;
    mapping& operator=(mapping const& other) noexcept = default;
    template<class OtherExtents>
      constexpr mapping& operator=(const mapping<OtherExtents>& other);

    Extents get_extents() const noexcept;
    array<ptrdiff_t, Extents::rank()> get_strides() const noexcept;

    constexpr typename Extents::index_type required_span_size() const noexcept;

    template <class... Indices>
      typename Extents::index_type operator()(Indices... is) const;

    static constexpr bool is_always_unique() noexcept;
    static constexpr bool is_always_contiguous() noexcept;
    static constexpr bool is_always_strided() noexcept;

    constexpr bool is_unique() const noexcept;
    constexpr bool is_contiguous() const noexcept;
    constexpr bool is_strided() const noexcept;

    ptrdiff_t stride(size_t rank) const noexcept;

  private:
    Extents extents_; // exposition only
    //TODO: should this be extents<dynamic_extent,...,dynamic_extent> ?
    array<ptrdiff_t, Extents::rank()> strides_; // exposition only
  };
};
```

## 26.7.�.3.1 layout_right::mapping constructors [mdspan.layout.right.cons]
```c++
constexpr mapping() noexcept;
```
* Effects: Default-initializes extents_.
* Postconditions: `get_extents() == Extents()` and `get_strides() == array<ptrdiff_t, Extents::rank()>()`

```c++
constexpr mapping(mapping const& other) noexcept;
```
* Effects: Initializes extents_ with other.extents_.
* Postconditions: `get_extents() == other.get_extents()` and `get_strides() == other.get_strides()`

```c++
constexpr mapping(mapping&& other) noexcept;
```
* Effects: Initializes extents_ with `move(other.extents_)`.
* Postconditions: `get_extents()` returns a copy of an Extents that is equal to the copy returned by `other.get_extents()` before the invocation of the move and `get_strides()` returns a copy of an `array<ptrdiff_t,Extents::rank()>` that is equal to the copy returned by `other.get_strides()` before the invocation of the move

```c++
constexpr mapping(Extents e, array<ptrdiff_t, Extents::rank()> s) noexcept;
```
* Requires: there is a permutation of the numbers `0,...,Extents::rank()-1` `o(i)` with `0 <= i < Extents::rank()` such that `stride(o(i)) >= stride(o(i-1))*get_extent(o(i-1))` for `1 <= i < Extents::rank()`
* Effects: Initializes extents_ with e and strides_ with s
* Postconditions: `get_extents() == e` and `get_strides() == s`.
* Throws: nothing

```c++
template<class OtherExtents>
  constexpr mapping(const mapping<OtherExtents>& other);
```
* Requires: other.get_extents() meets the requirements for use in the initialization of extents_.
* Effects: Initializes extents_ with other.get_extents() and initializes strides_ with other.get_strides().
* Postconditions: `get_extents() == other.get_extents()` and `get_strides() == other.get_strides()`.
* Remarks: This constructor does not participate in overload resolution unless OtherExtents is convertible to Extents.
* Throws: nothing.

## 26.7.�.3.2 layout_right::mapping operations [mdspan.layout.right.ops]

```c++
Extents get_extents() const noexcept;
```
* Returns: extents_.

```c++
Extents get_strides() const noexcept;
```
* Returns: strides_.

```c++
typename Extents::index_type required_span_size() const noexcept;
```
* Returns: The maximum of of `get_extents().extent(r) * stride(r)` for all `r` where `0 <= r < get_extents().rank()`

```c++
template <class... Indices>
  typename Extents::index_type operator()(Indices... i) const noexcept;
```
* Returns: If `i...` is `i0, i1, i2,..., ik` (where `k == Extents::rank() - 1`) and `s = get_strides()`, returns `i0*s[1] + i1*s[2] +...+ ik*s[k]`
* Remarks: This operator shall not participate in overload resolution unless
  * `sizeof...(Indices) == Extents::rank()`,
  * and `is_convertible_v<Indices, typename Extents::index_type> && ...`

```c++
static constexpr bool is_always_unique() noexcept;
static constexpr bool is_always_strided() noexcept;
constexpr bool is_unique() const noexcept;
constexpr bool is_strided() const noexcept;
```
TODO: should this be always unique?
* Returns: true

```c++
static constexpr bool is_always_contiguous() noexcept;
```
* Returns: false

```c++
constexpr bool is_contiguous() const noexcept;
```
* Returns: true if there is a permutation of the numbers `0,...,Extents::rank()-1` `o(i)` with `0 <= i < Extents::rank()` such that `min(stride(o(i)) == 1` and `stride(o(i)) == stride(o(i-1))*get_extent(o(i-1))` with `1 <= i < Extents::rank()` otherwise returns false

```c++
index_type stride(int r) const noexcept;
```
* Returns: `strides_(r)`

```c++
constexpr bool operator==(const mapping& other) const noexcept;
```
* Returns: `(get_extents() == other.get_extents()) && (get_strides() == other.get_strides())`

```c++
constexpr bool operator!=(const mapping& other) const noexcept;
```
* Returns: `(get_extents() != other.get_extents()) || (get_strides() != other.get_strides())`

**Comment by dhollman** [comment]
> * Postconditions: get_extents() == Extents() and get_strides() == array<ptrdiff_t, Extents::rank()>()

I'm pretty sure this would make `get_strides()` into uninitialized memory. I think what you'd actually want is `get_strides() == array<ptrdiff_t, Extents::rank()>{}`, though I'm not positive about this.

> **26.7.�.3.1 layout_right::mapping constructors**

This should be `layout_stride` (also a few other places)

> * Effects: Initializes extents_ with move(other.extents_).

Two things:
* Also needs "Initializes `strides_` with `std::move(other.strides_)`
* I think you're supposed to namespace-qualify `move` here so that it doesn't participate in ADL, though I'm not sure if the rest of the standard does this or not.

(Also need to make the analogous changes to the copy constructor.)

* `constexpr mapping(Extents e, array<ptrdiff_t, Extents::rank()> s) noexcept;`

Remove `noexcept` here; it has a requires clause so it can't be `noexcept`.


*more to come...*

**Comment by crtrott** [comment]
I think this is resolved
