### ISSUE TITLE
P0009 subspan wording

### ISSUE THREAD

**Issue by crtrott** [ORNL/cpp-proposals-pub#33]
Not quite done yet:
```c++
  // [mdspan.subspan], subspan creation
  template<class ElementType, class Extents, class LayoutPolicy,
           class Accessor, class... SliceSpecifiers>
    basic_mdspan<ElementType, E /* see-below */, layout_stride, Accessor>
      subspan(const basic_mdspan<ElementType, Extents, LayoutPolicy, Accessor>& src, SliceSpecifiers ... slices) noexcept;
```

* subspan creates a `basic_mdspan` that is a view on a (potentially trivial) subset of another `basic_mdspan`.
* The SliceSpecifier parameters indicate the subset that the return value references.
* Let slices[r] denote the rth value in the parameter pack slices.
* The second template parameter of the return type is E, a specialization of `extents`.
* Let `C` be the number of parameters in `SliceSpecifiers` which are convertible to `ptrdiff_t` 
* Let `ranges[r]` denote the rth value in the parameter pack slices, which is not convertible to `ptrdiff_t` 
* Let `sub` be the return value of `subspan`
* Let `first[r]` denote the rth lower bound of `slices[r]`. 
  * If `slices[r]` is convertible to `ptrdiff_t` `first[r]==slices[r]`
  * If `slices[r]` is convertible to `pair<ptrdiff_t,ptrdiff_t>` `first[r]==pair<ptrdiff_t,ptrdiff_t>(slices[r]).first()`
  * If `slices[r]` is convertible to `alltype_t` `first[r]==0`
* Let `last[r]` denote the rth upper bound of `slices[r]`. 
  * If `slices[r]` is convertible to `ptrdiff_t` `last[r]==slices[r]+1`
  * If `slices[r]` is convertible to `pair<ptrdiff_t,ptrdiff_t>` `last[r]==pair<ptrdiff_t,ptrdiff_t>(slices[r]).second()`
  * If `slices[r]` is convertible to `alltype_t` `last[r]==src.extent(r)`
* Requires: 
  * `sizeof(slices...)==Extents::rank()`
  * `slices[r]` is convertible to `ptrdiff_t`, `pair<ptrdiff_t,ptrdiff_t>` or `alltype_t`
  * `0<=first[r]<src.extent(r)`
  * `0<last[r]<=src.extent(r)`
  * `LayoutPolicy` is `layout_right`, `layout_left`, or `layout_stride`
* Postcondition:
  * `E::rank() == Extents::rank()-C`
  * If `ranges[r]` is the nth value of `ranges` convertible to `alltype_t` or `pair<ptrdiff_t,ptrdiff_t>` and `slices[k]` is the `n`th value of `slices` convertible to `all type_t` or  `pair<ptrdiff_t,ptrdiff_t>` then `sub.extent(r)==last[k]-first[k]` and `sub.stride(r)==src.stride(k)`
  * `sub.ptr_==src.ptr_ + first[0]*src.stride(0) + ... + first[Extents::rank()-1]*src.stride(Extents::rank()-1)`
* Note: it is quality of implementation whether static extents are preserved if possible. 
* Examples:
```c++
typedef extents<100,dynamic_extent,3> Extents3D;
layout_right::mapping<Extents3D> map_right(
basic_mdspan<int,Extents3D,layout_right> a()
```

**Comment by mhoemmen** [comment]
@crtrott It looks like this isn't in the paper yet -- should I add this, or wait for a PR?

**Comment by crtrott** [comment]
No this isn't done yet. We need to finish this definition first. Its kind of complicated ;-)

**Comment by crtrott** [comment]
Check whether this is postcondition or return clause.

**Comment by crtrott** [comment]
Closing this for now. We got a working definition committed.
