### ISSUE TITLE
P0009: View?

### ISSUE THREAD

**Issue by mhoemmen** [ORNL/cpp-proposals-pub#42]
The current C++ draft defines `span` as a "view."  P0009 also defines `mdspan` as a "view."  I don't see a clear definition of "view" anywhere in the draft, even with `string_view`.  I understand what "view" means -- something that accesses something else without owning it -- but I wonder if the Standard needs to define some concepts, in the same way that it defines various concepts for the Container section.

**Comment by crtrott** [comment]
According to David this is gonna come in via the Ranges TS.
