### ISSUE TITLE
P0009: Example at Line 1758 looks incomplete, breaks bikeshed

### ISSUE THREAD

**Issue by mhoemmen** [ORNL/cpp-proposals-pub#44]
https://github.com/ORNL/cpp-proposals-pub/blob/9bbb0ddae0de09e192dc447408c17e9cc3819426/P0009/P0009.bs#L1759

Bikeshed complains about those lines:
```
$ bikeshed spec P0009.bs
FATAL ERROR: Line 1758 isn't indented enough (needs 1 indent) to be valid Markdown:
"<xmp class='language-c++'"
 ✘  Did not generate, due to fatal errors
```
When I delete the code example, Bikeshed runs just fine.  Also, the example looks incomplete and not really related to the stuff above it, as if some lines got deleted.

**Comment by mhoemmen** [comment]
@crtrott @dhollman @dsunder @hcedwar

**Comment by mhoemmen** [comment]
ok Christian is working on this so I'll close and track in #47; thanks!

**Comment by hcedwar** [comment]
Fresh pull and still getting this error.

**Comment by mhoemmen** [comment]
Dan recommends `bikeshed -f spec P0009.bs` for now; I tried it, and it seems to help for now.

**Comment by crtrott** [comment]
we fixed this. There was a blank line missing before opening a code section
