### ISSUE TITLE
P0009: open questions to be resolved

### ISSUE THREAD

**Issue by crtrott** [ORNL/cpp-proposals-pub#47]
*  DS: check for returns vs effects
* extent
  *  ~DS: Copy constructors: Should this be two different sections, or does it not matter for move initialization of array? -> *agreed: all constructors, copy and assignment one section*~
  *  ~DS: review change to make rank() and rank_dynamic() size_t -> Does that conflict with extent(int r)? -> *agreed: Everything size_t to align with 23.15.5 in n4750*~
  *  ~DS: review addition of array constructor -> *agreed: yes: replace N with rank_dynamic, delete remark N==rank_dynamic*~
  *  ~DS: review addition of compatible extents constructor -> *agreed: yes, but needs to remove noexcept, add throws nothing*~
  * ~DS: Sequence constructor: look at how parameter pack expansions are specified in, e.g., integer_sequence~
  * ~Do we need initializer list constructor? *agreed: no*~
* Layout
  * ~DS: Sentence 2 not complete in layout_stride description~
  * ~CT: should all ptrdiff_t be Extents::index_type? -> *agreed: YES*~
  * ~CT: i... and j... definition some conditions are only made for i do we need to add them for j? -> *agreed: add clauses for j, remove "for i... and j..."*~
  * ~CT: definition of is_contiguous ok? -> *set of values and set notation for interval*~
  * ~stride(r) -> should this not be callable or return dummy value if is_strided()==false -> *Required clause sufficient*~
  * ~Review minor design change consolidating extents-like member functions into get_extents() -> *agreed: OK*~
  * ~conversion from other layouts? -> *agreed: Don't do it now*~
  * ~review addition of copy construction from same mapping with different compile time extents -> *agreed: OK*~
  * ~CT: Choose wording of copy construction from same mapping with different compile time extents: initialization or assignment -> *agreed: use initialization, remove remark which duplicate require clause*~
  * ~CT: add comparison with different extent type like on extents? -> *agreed: YES as member function*~
  * ~layout_stride: exposition only member array or extents? -> *agreed: array*~
  * ~CT: layout_stride: is_always_unique==true? -> *agreed: YES need requirement stride(r)>0*~
* Accessor:
  * ~review whether these requirements are flexible enough -> *agreed: YES*~
  * This was too hard to specify as a nested class, and I'm not sure it buys us anything. (specifically, it was getting really messy trying to allow accessor implementations to constrain what types they are valid for.) -> *proposed: OK*
  * ~MH: check wording for a(p,i) and check the note: *not clear*~
* subspan
  * CT: Check whether this is postcondition or return clause. -> *agreed: make it a return clause*\
  * ~CT: fix example~
* mdspan: 
  * ~MH: add section reference in synopsis~
  * ~do we need converting move constructor? -> *agreed: no: size of object may change*~
  * ~review get_mapping and get_extents -> *agreed: OK*~
  * ~MH: consistent set of constructors with description: const&, pointer vs span: *agreed: pointer not by const&~
     * ~MH: check require clauses, and effects clauses like zero-initialize of ptr~
     * ~MH: remove remarks for default_constructible of mapping and accessor~
     * ~MH: write all the constructor wordings~
     * ~MH: make default constructor and copy constructor default~
  * ~span excludes default constructor if there are no dynamic extents.  Should we do the same? -> *agreed: NO also we don't have a data function which makes this less confusing*~
  * ~DS: prefer is_integral_v<IndexType>&& ... over is_convertible<IndexType, index_type>&&....)? -> *agreed: No*~
  * ~for operator which takes array Do I need a requires clause if I already have an equivalent effects clause?~

**Comment by mhoemmen** [comment]
Some formatting issues too -- Bikeshed breaks on e.g., line 2423, which looks like an incomplete example.

**Comment by mhoemmen** [comment]
> Copy constructors: Should this be two different sections, or does it not matter for move initialization of array?

`span` (and all the other Containers) name the corresponding section "constructors, copy, and assignment".  All those three things go into the one section.

**Comment by mhoemmen** [comment]
> Sequence constructor: look at how parameter pack expansions are specified in, e.g., `integer_sequence`

n4750, Section 23.3, p. 497

```c++
     namespace std {
       template<class T, T... I> struct integer_sequence {
         using value_type = T;
         static constexpr size_t size() noexcept { return sizeof...(I); }
       };
}
```

**Comment by mhoemmen** [comment]
`index_sequence` is more like what you want -- see p. 494, Section 23.2.1, "Header `<utility>` synopsis".

**Comment by mhoemmen** [comment]
@crtrott wrote:
> Do we need initializer list constructor

I would say no.  `extents` is like `integer_sequence`, which doesn't have an `initializer_list` constructor.

Containers (SequenceContainer, AssociativeContainer, UnorderedAssociativeContainer, etc.) have `initializer_list` constructors, as do `optional`, `variant`, `any` (or at least via `make_any`),  `basic_string`, the SeedSequence concept for pseudorandom number generators, and a few other things that aren't like `integer_sequence`.

**Comment by mhoemmen** [comment]
@crtrott wrote:
> `stride(r)` -> should this not be callable or return dummy value if `is_strided()==false`

Precedent for "should not be callable" in the current Standard: Iterators.

**Comment by mhoemmen** [comment]
That is, there is a hierarchy of Iterator concepts, and only some of them support certain syntax.

**Comment by mhoemmen** [comment]
C++ seems to be moving away from requiring traits classes like `iterator_traits`, and towards `if constexpr` etc.  Users could write code like this:
```c++
if constexpr (x.is_strided ()) {
  // ... get the strides, call some Fortran code, etc. ... 
}
else {
  // ... e.g., copy into a LayoutLeft View before calling Fortran ...
}
```

**Comment by mhoemmen** [comment]
@crtrott wrote:
> definition of `is_contiguous` ok?

What does "ok" mean here?  I'm guessing you mean the wording of the definition of `is_contiguous`:

> true if the set values defined by `m(i)...` is equal to `[0..m.required_span_size())`

Could we use `integer_sequence` to define this?  Say, `integer_sequence<ptrdiff_t, m(i)...> == make_integer_sequence<ptrdiff_t, m.required_span_size() >` ?

**Comment by mhoemmen** [comment]
Oh wait, does "set values" mean "unordered"?  As in, "is some permutation of"?

**Comment by crtrott** [comment]
Yeah it means some permutation with elimination of duplicates ...

**Comment by hcedwar** [comment]
typo "set of values"

**Comment by hcedwar** [comment]
- review change to make rank() and rank_dynamic() : *[meta.unary.prop.query]* `rank` and `extent` metafunctions have integer values
- stride(r) -> should this not be callable or return dummy value if is_strided()==false : no need to specify, statement that **requires** `is_strided()` makes it *UB* to call it.
- layout_stride: is_always_unique==true? : NO, example is BLAS use where the stride is set to zero to use a single source value

**Comment by dhollman** [comment]
> stride(r) -> should this not be callable or return dummy value if is_strided()==false : no need to specify, statement that requires is_strided() makes it UB to call it.

Shouldn’t it just return 1? Why do we need to be fancy about this?

**Comment by dhollman** [comment]
> layout_stride: is_always_unique==true? : NO, example is BLAS use where the stride is set to zero to use a single source value
 
okay, but then we need more constructors to express this. Alternatively, you can just handle that case with a custom layout. Also, subspan is really hard to specify without this restriction.  We can always relax it later.

**Comment by dhollman** [comment]
> review change to make rank() and rank_dynamic() : [meta.unary.prop.query] rank and extent metafunctions have integer values

If you don’t like this change, please go through the proposal and add narrowing casts to all of the semantics that involve `sizeof`

**Comment by mhoemmen** [comment]
@hcedwar wrote:
> NO, example is BLAS use where the stride is set to zero to use a single source value

I feel like that should be a custom layout.  You can't declare a Fortran array like that -- it's just a trick for calling the BLAS.

**Comment by mhoemmen** [comment]
@hcedwar wrote:
> NO, example is BLAS use where the stride is set to zero to use a single source value

Although, nothing forbids creation with zero strides, or even negative strides, right?

**Comment by mhoemmen** [comment]
The BLAS allows negative strides, and the reference BLAS implements this with special cases.

**Comment by mhoemmen** [comment]
ADD: reword beginning

**Comment by mhoemmen** [comment]
@crtrott wrote:
> MH: check wording for a(p,i) and check the note: not clear

Here's my suggestion: https://github.com/ORNL/cpp-proposals-pub/pull/48

**Comment by mhoemmen** [comment]
mdspan fixes, part 1: https://github.com/ORNL/cpp-proposals-pub/pull/49

**Comment by mhoemmen** [comment]
Here's what I need to do for `mdspan` yet:

> MH: check require clauses, and effects clauses like zero-initialize of ptr
> MH: write all the constructor wordings

**Comment by mhoemmen** [comment]
I can't figure out how section header links work in bikeshed; nothing I try seems to work, including examples from JF's papers.  I'm giving up and just putting in the `[**section-name**]` thing.

**Comment by mhoemmen** [comment]
https://github.com/ORNL/cpp-proposals-pub/pull/50 fixes the following for `basic_mdspan` constructors:

  - Check require and effects clauses
  - Write all the constructor wordings
  - Consistently use `span<element_type>` (`dynamic_extent`) as `basic_mdspan` constructor input
  - Add requirement on span size

**Comment by mhoemmen** [comment]
https://github.com/ORNL/cpp-proposals-pub/pull/52 adds section headings to the various synopses.

**Comment by crtrott** [comment]
I think is worked down.
