### ISSUE TITLE
Accessor abstraction (PR #55)

### ISSUE THREAD

**Issue by hcedwar** [ORNL/cpp-proposals-pub#56]
Accessor abstraction discussion as manifested in PR #55 

Current PR #55 re-conceives the accessor abstraction a something similar to an array of unknown bound when it is used as a function parameter.  It specifically avoids redefining _pointer_ and only defines the _reference_ type returned by the subscripting operator.

**Comment by crtrott** [comment]
Couple questions: 

Can we assume you intend to do
```c++
using pointer = Accessor;
```
instead of
```c++
using pointer = ElementType*;
```
in mdspan? 
Otherwise your accessor thing would not be used anywhere. I.e. we wouldn't need to define it. 

Assuming this is what you meant we now need to define subspan via intermediate conversion of ptr to `ElementType*`. In order for that to be valid we would need to require that
`subspan.ptr_[i] == (Accessor( (ElementType*(ptr_)) + i))[0]`
But isn't that going against what you want for requirements? Effectively this means that an arbitrary offset capability exists - i.e. you bought that vast majority of random access iterator requirements along.

**Comment by crtrott** [comment]
David came up with an idea earlier which might give you also what you need without to much complicated definition stuff. Basically it is adding an offset function to accessor which generates a new pointer from an existing one with an offset added. 
Something like this:
```c++
template<class T>
struct accessor {
  typedef ... pointer;
  typedef ... reference;
  pointer offset(pointer,ptrdiff_t);
  reference operator(pointer,ptrdiff_t);
};
```
This way pointer could just be a very basic thing with copy constructible etc. but doesn't need to be random iterator which we mainly needed to do the subspan in a sane way. Now we could use offset() do get the subspan implementation, and we don't need to define complicated semantics of an [] operator on pointer. ​

**Comment by dhollman** [comment]
Slight changes, but basically the same:
```c++
struct accessor {
  using value_type = /* ... */;
  using pointer = /* ...CopyConstructible, DefaultConstructible... */;
  using reference = /* requires operator*() convertible to value_type, assignment from value_type */;
  pointer offset(pointer, Integral);
  reference dereference(pointer);
};
```

**Comment by dhollman** [comment]
Updated:

```c++
struct accessor {
  using value_type = /* ... */;
  using pointer = /* ...CopyConstructible, DefaultConstructible... */;
  using reference = /* requires operator*() convertible to value_type, assignment from value_type */;
  pointer offset(pointer, Integer);
  reference operator()(pointer, Integer);
};
```

**Comment by crtrott** [comment]
The requirement we would put into this accessor would be that:
```c++
a(a.offset(pointer,i),0) == a(pointer,i);
```
That then takes care of subspan being well defined.

**Comment by dhollman** [comment]
We can probably also get away with the requirement that the second argument to `offset` and `operator()` must be `>= 0` (but not necessarily unsigned, of course).

**Comment by crtrott** [comment]
Yeah I agree that should be fine. I could imagine complex layouts where you wouldn't want that but we probably could relax that requirement later if need be.

**Comment by dhollman** [comment]
@crtrott We can't quite make that requirement, since we don't require `operator==` on `value_type`. We'd probably want something like "effects equivalent to" or something like that.

**Comment by crtrott** [comment]
Yeah something like that.

**Comment by hcedwar** [comment]
Just updated the PR to replace exposition references to `ptr_` with `acc_`.

**Comment by hcedwar** [comment]
re: subspan, updated wording to explicitly convert to pointer before making the offset and equality comparison.

**Comment by crtrott** [comment]
We still need to say something about the relationship of `acc_[i] == Accessor((T*(acc_))+i)[0]` or something like this.

**Comment by hcedwar** [comment]
`acc_[i]` refers to the same element as `*(((T*)acc_)+i)`
Note the reference may not be pointer equality, consider the Kokkos texture case where is return by value.

**Comment by hcedwar** [comment]
Major theme in abstraction is that `T*` fulfills requirements for accessor, a random access iterator could also fulfill requirements, but there are other more restrictive possibilities.

**Comment by crtrott** [comment]
If we require `acc_[i]` refers to the same element as `*(((T*)acc_)+i)` doesn't that defeat the purpose of what you wanted to do initially?

**Comment by hcedwar** [comment]
In the wording I say _accesses_, not references to avoid implying a `T&` reference type.

**Comment by hcedwar** [comment]
`acc_[i]` can return a value if `T` is `const`, or other reference-proxy type that is not `T&`

**Comment by crtrott** [comment]
Thats not what I meant I was talking about alignment issues etc. (and the refers was a direct quote from your above comment). But you are confident this would give you everything you need?

**Comment by hcedwar** [comment]
Conversion to `T*` would discard any alignment attribute.

**Comment by hcedwar** [comment]
In fact, conversion to `T*` would discard any special provisions introduced by the accessor.

**Comment by crtrott** [comment]
But do you require that for any `i` `Accessor(p+i)` is valid?

**Comment by hcedwar** [comment]
Nope; in my prototype of `accessor_aligned` the constructor has `assert( 0 == reinterpret_cast<uintptr_t>(p) % align )`

**Comment by hcedwar** [comment]
_Accessor_ dependent requirements for `Accessor(p)`

**Comment by crtrott** [comment]
OK if the goal of this exercise is to explicitly support that we would need to put normative wording into the proposal to this effect. Or do you believe that the proposal (including with your update) doesn't require this arbitrary assignment to be valid? I think the subspan stuff implies that this must work.

**Comment by hcedwar** [comment]
Subspan is free to generate different extents, layout, and accessor. I updated the wording accordingly.

**Comment by dhollman** [comment]
@hcedwar Can you clarify why doesn't what I gave above support your use case? The accessor above is something we're much more comfortable with.

**Comment by hcedwar** [comment]
1. Given `accessor<T>::pointer p(...)` then `accessor<T>::offset(p,1)` may not be able to return an `accessor<T>::pointer` that satisfies the requirements of `accessor<T>`; e.g., the `accessor_aligned` use case.  This is the major item.
1. Continuing to simplify abstraction; e.g., `T*` can now satisfy `accessor` requirements so `accessor_basic` is unnecessary.
1. Composition of multi-index mapping and accessor mapping is simply `acc_[ mapping_(i0,i1,...) ]`
1. Accessor can be easily used outside of mdspan as a drop-in replacement for `T[]` function argument, or attaching attributes to a `T*const`; e.g., `auto a = access_via_foo(p)`.

@dhollman Can you clarify why uncomfortable with current proposal?

**Comment by dhollman** [comment]
> Given accessor<T>::pointer p(...) then accessor<T>::offset(p,1) may not be able to return an accessor<T>::pointer that satisfies the requirements of accessor<T>; e.g., the accessor_aligned use case. This is the major item.

That's fine. It's allowed to throw or abort, just like your proposed `aligned_accessor` constructor, except that it doesn't have all of the negative connotations associated with a constructor that throws (e.g., leaves the object in a partially constructed state).

> Continuing to simplify abstraction; e.g., T* can now satisfy accessor requirements so accessor_basic is unnecessary.

We still have quite a number of use cases that can't be handled by this. @crtrott is working up an email now about this. I'll add some later if he doesn't address this.

> Composition of multi-index mapping and accessor mapping is simply acc_[ mapping_(i0,i1,...) ]

That's not significantly more complex than `acc_(ptr_, mapping_(i0,i1,...))`. However, when it does something more than just access (like create an atomic), you're hiding functionality behind `operator[]`, which is generally discouraged AFAICT. Also, `operator[]` is traditionally non-throwing (think `std::vector`), so using it for something that can throw would be an antipattern.

> Accessor can be easily used outside of mdspan as a drop-in replacement for T[] function argument, or attaching attributes to a T*const; e.g., auto a = access_via_foo(p).

That's absolutely true of my design also, except my design doesn't have all of the negative baggage associated with abusing `operator[]`.  See, for instance, core guideline C.167

**Comment by crtrott** [comment]
One example of what doesn't work with your proposal Carter is texture objects. In particular subspan of texture objects are not possible. The same is true for reference counting. The only connection from the storage point of view between an mdspan and the subspan occurs now via `T*`. Consequently we can not track and additional information across the boundary. For reference counting that means we can not connect the reference count of the two, and for texture objects we can't do it since they must be constructed on the host (i.e. we loose the ability to do a device side subspan). Both of those things work right now in Kokkos. This is one of the big reasons for us having either random access iterator as the requirement for pointer or using an offset function. We need some way of creating an offseted pointer without going through conversions.

**Comment by hcedwar** [comment]
...awaiting the use cases
`operator[]` should not throw, all error check should take place in _accessor_ constructor and then everything is smooth sailing from that point onward.  This is the pattern in `atomic_ref` which has been accepted into the working draft.
Given:
```
void blas( const double x[] , double y[] , size_t n )
{
  for ( size_t i = 0 ; i < n ; ++i ) y[i] = y[i] + x[i];
}
```
with
```
void blas( accessor_foo<const double> x , accessor_foo<doulble> y , size_t n )
{
  for ( size_t i = 0 ; i < n ; ++i ) y[i] = y[i] + x[i];
}
```
is far less churn than
```
void blas( typename accessor<const double>::pointer x , typename accessor<double>::pointer y , size_t n )
{
  accessor<double> Ay{};
  accessor<const double> Ax{};
  for ( size_t i = 0 ; i < n ; ++i ) Ay(y,i) = A(y,i) + Ax(x,i);
}
```

**Comment by crtrott** [comment]
One more thing is that I believe that we can implement all the functionality you want through our accessor which is not true the other way around. The two things you wouldn't get is that 
1) `T*` is a valid accessor
2) convertibility of `pointer` to `T*`, which we simply could require, but explicitly didn't, because it would prevent certain use cases we are interested in such as supporting segmented memory spaces.

```c++
template<class SandiaAccessor>
class CarterAccessor {
  SandiaAccessor::pointer ptr_;
  SandiaAccessor a;
  void operator[] (ptrdiff_t i) { return a(ptr_,i); }
};
```
There is not way to implement `offset` using your accessor concept which kill the texture object subspan and reference counting subspan use case.

**Comment by crtrott** [comment]
So are you saying accessor in your mind should be used as a first class data container itself? We always considered accessor as a thing to change access semantics and nothing more, and that is how it was sold to the committee as far as I can tell. Introducing it as a new data container is a whole different matter isn't it?

**Comment by hcedwar** [comment]
Not a container, a _view_.

**Comment by crtrott** [comment]
Sure so you want to introduce a new view like span.

**Comment by hcedwar** [comment]
`Kokkos::Impl::CudaTextureFetch` is an _accessor_
The Kokkos vision was that `Kokkos::View` would someday use `mdspan` in its implementation, not a 100% replacement, because `mdspan` is non-owning or even non-sharing.

**Comment by hcedwar** [comment]
Sure you can.  A type is not restricted to have **only** the _accessor_ required interface, it can have more so the Texture object can be copied and the offset updated.

**Comment by hcedwar** [comment]
lol - two parallel discussions being serialized.

**Comment by crtrott** [comment]
But wouldn't that mean that what subspan actually does is implementation defined? If I can't offset the accessor itself that means we would need to do some serious wording on what it means to create an subspan. In the current wording it would be legal for my accessor to set m_offset to zero during the subspan creation, because the only information I can reliably use inside the subspan implementation is that I can convert mdspan.acc_ into `T*` and use that `T*` to construct my new accessor.

**Comment by crtrott** [comment]
In particular what would the post condition be? Right now we only have postcondition which describe the extents object and then this
```
(pointer)sub.acc_==((pointer)src.acc_)+first[0]*src.stride(0)+...+first[Extents::rank()-1]*src.stride(Extents::rank()-1) 
```

**Comment by hcedwar** [comment]
`subspan` needs to understand how to map extents, layouts and accessor.  Some accessors may not be preservable across the subspan, others may be.

**Comment by hcedwar** [comment]
A `T*` accessor will always be mappable.

**Comment by crtrott** [comment]
OK so we have to come up with a the set of post conditions we need to express exactly what a subspan does and then say that for every accessor where must exist a subspan partial specialization.

**Comment by hcedwar** [comment]
... btw, that postcondition is probably insufficient

**Comment by crtrott** [comment]
in the R7 the postconditions were enough, since subspan is only defined for the three layouts provided by the paper (there is a requires clause that Layout is either layout_righ, layout_left or layout_stride). More generally the post conditions in R7 were enough for any layout for which is_always_strided is true  .

**Comment by dhollman** [comment]
> `subspan` needs to understand how to map extents, layouts and accessor. Some accessors may not be preservable across the subspan, others may be.

This implies that for a custom accessor, `subspan` must be a customization point. It really doesn't have the form of modern customization points, so I'd be pretty uncomfortable going down that road.

**Comment by hcedwar** [comment]
Layout and Accessor are both customization points.
I updated PR #55 to reflect the downstream influence of accessor customization on subspan.  When accessor is simply a pointer then there is no impact, when customized the accessor defines the subsequent accessor-offset type to plug into subspan.

**Comment by hcedwar** [comment]
PR #55 prototype includes customization of Accessor Policy that plugs in `std::shared_ptr`  as an example of extensibility.

**Comment by crtrott** [comment]
I believe this is resolved for now with a solution which appears to be acceptable to all parties involved? Please reopen if you have more issues with this.
