### ISSUE TITLE
New version of P0454 dramatically departs from prior version, fails to cite history

### ISSUE THREAD

**Issue by hcedwar** [ORNL/cpp-proposals-pub#7]
[P0454r0](https://github.com/kokkos/array_ref/blob/master/proposals/P0454r0.bs) titled "Proposed wording, based on span P0122R] for an mdspan with a core subset of the full mdspan functionality" emphasized span and mdspan interoperability.  The [version 1 revision](https://github.com/ORNL/cpp-proposals-pub/blob/master/P0454/P0454r1.bs) titled "Proposed wording for mdspan" drops the [P0454r0](https://github.com/kokkos/array_ref/blob/master/proposals/P0454r0.bs) span-alignment scope, predominantly pulls significant content from (p0009)[https://github.com/kokkos/array_ref/blob/master/proposals/P0009.rst], and drops numerous P0009 authors some of whom were integral to the years of design-investment in mdspan, without even citing P0009.

**Comment by brycelelbach** [comment]
Additonally I'm not sure why this paper was added to this repo, it is in
other places.

**Comment by crtrott** [comment]
We are closing down the paper repository in the Kokkos organization. Carter was aware of that.
