### ISSUE TITLE
Reference implementation constructor signatures for basic_mdspan do not match P0009r8

### ISSUE THREAD

**Issue by blauc** [ORNL/cpp-proposals-pub#91]
basic_mdspan constructors that take const x &  parameters in P0009r8, take only const x in the reference implementation.

**Comment by crtrott** [comment]
We are going through another rewrite of the proposal based on a review session at the SanDiego meeting. After that is done we will update the reference implementation to get into alignment again. But feel free to issue pull requests if you see something now.

**Comment by dhollman** [comment]
We have a new version of the reference implementation available now; see <https://github.com/kokkos/mdspn>
