### ISSUE TITLE
In basic_mdspan static_extent may become static

### ISSUE THREAD

**Issue by blauc** [ORNL/cpp-proposals-pub#97]
https://github.com/ORNL/cpp-proposals-pub/blob/55a84e52a446f39fee37550a9dd483ee5888e14c/P0009/reference-implementation/include/experimental/bits/mdspan.hpp#L170-L171

Above may be static when instead using `return extents_type::static_extent(k);` - allowing compile time assessment of static_extents.

**Comment by dhollman** [comment]
Yeah, this is a bug on our part.  This method is static in the proposal.  I'll put in a fix.

**Comment by dhollman** [comment]
should be fixed now
